@TodoApi_HostAddress = http://localhost:5165/api/todoitems/

GET {{TodoApi_HostAddress}}/1
Accept: application/json

###

POST {{@TodoApi_HostAddress}}/1
Accept: application/json

{
    "id": 0,
    "name": "tarea",
    "isComplete": false 
}

###
